///Harvard Art Data in case api freaks out again
{
  "info": {
    "totalrecordsperquery": 50,
    "totalrecords": 23157,
    "pages": 464,
    "page": 1
  },
  "records": [
    {
      "id": 295575,
      "technique": null,
      "title": "Sketches of a Girl",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:VRS18398_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "18th century",
      "dated": "18th century",
      "period": null,
      "medium": "Red chalk on off-white antique laid paper",
      "culture": "Italian"
    },
    {
      "id": 170066,
      "technique": null,
      "title": "Water Scene with Figures in Rowboats",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:78388_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1878",
      "period": null,
      "medium": "Graphite on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 294912,
      "technique": null,
      "title": "Portrait of a Young Man",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:71312_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "17th century",
      "dated": "17th century",
      "period": null,
      "medium": "Black and white chalk on blue paper, faded to gray-beige, partial framing line in black ink",
      "culture": "Dutch"
    },
    {
      "id": 161958,
      "technique": null,
      "title": "Untitled [Women Sweeping]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV123607_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "undated",
      "period": null,
      "medium": "Black crayon on paper",
      "culture": "German?"
    },
    {
      "id": 161968,
      "technique": null,
      "title": "Untitled [Legefeld]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV104345_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1913",
      "period": null,
      "medium": "Green crayon on paper",
      "culture": "German"
    },
    {
      "id": 295953,
      "technique": null,
      "title": "Blank page; verso: Half-length Figure Study",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:73206_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "18th century",
      "dated": "c. 1758",
      "period": null,
      "medium": "Graphite on off-white antique laid paper",
      "culture": "French"
    },
    {
      "id": 306640,
      "technique": null,
      "title": "Beacon Street Mall, Boston",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV000704_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "20th century",
      "period": null,
      "medium": "Graphite on heavy cream wove paper",
      "culture": "American"
    },
    {
      "id": 307169,
      "technique": null,
      "title": "Sailboats on the Nile",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV010179_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th-20th century",
      "dated": "19th-20th century",
      "period": null,
      "medium": "Watercolor on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 190718,
      "technique": null,
      "title": "Study of the Artist Standing Sketching; Lowered Banners; Profile Caricature; verso: Facade of a Building",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:20994_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1805-1824",
      "period": null,
      "medium": "Graphite with accents in black crayon, standing figure squared in graphite, on off-white antique laid paper; verso: black crayon",
      "culture": "French"
    },
    {
      "id": 308081,
      "technique": null,
      "title": "Pont de Nant, France",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV004915_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1929",
      "period": null,
      "medium": "Black, white, and colored pastel on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 295543,
      "technique": null,
      "title": "Immaculate Conception",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:71556_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "17th-18th century",
      "dated": "c. 1700",
      "period": null,
      "medium": "Brown ink, brown wash and white gouach over black chalk on white antique laid paper",
      "culture": "Flemish"
    },
    {
      "id": 310247,
      "technique": null,
      "title": "\"Rape of the Sabines,\" after Giambologna, Loggia dei Lanzi, Florence",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:huam:DDC112096_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "c. 1906-1910",
      "period": null,
      "medium": "Graphite on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 198208,
      "technique": null,
      "title": "Shrines in the Forest",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:77431_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1871",
      "period": null,
      "medium": "Graphite on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 102042,
      "technique": null,
      "title": "Sketchbook page",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:62242_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "18th century",
      "dated": "c. 1776",
      "period": null,
      "medium": "Black chalk on cream antique laid paper",
      "culture": "French"
    },
    {
      "id": 162572,
      "technique": null,
      "title": "Untitled [Boats]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV114358_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "7/21/1929",
      "period": null,
      "medium": "Graphite on paper",
      "culture": "German"
    },
    {
      "id": 163525,
      "technique": null,
      "title": "Untitled [Factory Smokestacks]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV107035_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "8/12/1922",
      "period": null,
      "medium": "Graphite on paper",
      "culture": "German"
    },
    {
      "id": 309649,
      "technique": null,
      "title": "Untitled",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV007093_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1953",
      "period": null,
      "medium": "Black ink, graphite, and yellow ink on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 312506,
      "technique": null,
      "title": "St. Bartholomew",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV001985_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "18th-19th century",
      "dated": "18th-19th century",
      "period": null,
      "medium": "Gray wash and black ink over graphite on cream wove paper",
      "culture": "Austrian"
    },
    {
      "id": 309593,
      "technique": null,
      "title": "Untitled",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV006962_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1950 - 1953",
      "period": null,
      "medium": "Black ink, graphite, and yellow chalk on cream wove paper",
      "culture": "American"
    },
    {
      "id": 166294,
      "technique": null,
      "title": "Pennsylvania Pavilion for World's Fair, New York, 1939: Hall of Tradition, toilet rooms: plan, elevations, sections,  (1/4\" , 1/2\" and 3\"  = 1'-0\")",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:DDC110314",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1939",
      "period": null,
      "medium": "Graphite on paper",
      "culture": "American"
    },
    {
      "id": 297230,
      "technique": null,
      "title": "Study of Arabs",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:758424",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1832",
      "period": null,
      "medium": "Graphite and watercolor on white wove paper",
      "culture": "French"
    },
    {
      "id": 295740,
      "technique": "Counterproof",
      "title": "Three Soldiers Looking at a Map; verso: Strolling Soldier (counterproof)",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:VRS17092_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "17th century",
      "dated": "17th century",
      "period": null,
      "medium": "Red chalk on cream antique laid paper, laid down on verso of counterproof",
      "culture": "Italian"
    },
    {
      "id": 297194,
      "technique": null,
      "title": "Landscape",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV005447_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "19th century",
      "period": null,
      "medium": null,
      "culture": "French"
    },
    {
      "id": 162397,
      "technique": null,
      "title": "Untitled [Sea and Sky]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV119107_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "7/1/1932",
      "period": null,
      "medium": "Graphite on paper and mounted",
      "culture": "German"
    },
    {
      "id": 219633,
      "technique": null,
      "title": "Study of a Seated Man and Women's Heads",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV015184_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "19th-20th century",
      "dated": "19th-20th century",
      "period": null,
      "medium": "Paper",
      "culture": "German"
    },
    {
      "id": 163197,
      "technique": null,
      "title": "Untitled [Sea and Sky]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV108424_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "8/10/1924",
      "period": null,
      "medium": "Graphite on paper, mounted",
      "culture": "German"
    },
    {
      "id": 306405,
      "technique": null,
      "title": "Edge of the Village, Deurle, Belgium",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:36304_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1905",
      "period": null,
      "medium": "Crayon with scratchwork on off-white illustration board",
      "culture": "American"
    },
    {
      "id": 305415,
      "technique": null,
      "title": "Bearded Man with a Stick, for \"Jason Returning to Demand his Father's Kingdom\"",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV000902_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "c. 1807",
      "period": null,
      "medium": "Black and white chalk on blue-gray wove paper",
      "culture": "American"
    },
    {
      "id": 306054,
      "technique": null,
      "title": "The Crocodile Rejected, for \"The Crocodile,\" by Oliver Herford",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:LEG001555_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1891",
      "period": null,
      "medium": "Black ink over graphite on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 296247,
      "technique": null,
      "title": "La Tour Saint-Jacques",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:VRS41871_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "19th century",
      "period": null,
      "medium": "Graphite on buff wove paper",
      "culture": "French"
    },
    {
      "id": 164294,
      "technique": null,
      "title": "Untitled [Figures Walking with Umbrellas]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV100765_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "6/16/1912",
      "period": null,
      "medium": "Graphite on paper",
      "culture": "German"
    },
    {
      "id": 163870,
      "technique": null,
      "title": "Untitled [Village Road]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV102269_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "4/8/1913",
      "period": null,
      "medium": "Black crayon on paper",
      "culture": "German"
    },
    {
      "id": 298594,
      "technique": null,
      "title": "St. Sebastian",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:71535_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "17th century",
      "dated": "17th century",
      "period": null,
      "medium": "Brown ink and gray wash over graphite, squared in graphite, on light tan antique laid paper",
      "culture": "Flemish"
    },
    {
      "id": 309871,
      "technique": null,
      "title": "Endymion (II)",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV181501_dynmc",
      "department": "Department of Drawings",
      "description": "Pinholes at all corners.",
      "classification": "Drawings",
      "century": "20th century",
      "dated": "20th century",
      "period": null,
      "medium": "Watercolor (with wax resist) and graphite on white wove paper",
      "culture": "American"
    },
    {
      "id": 221296,
      "technique": null,
      "title": "Boats with Clouds",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV155614_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1922",
      "period": null,
      "medium": "Graphite on paper",
      "culture": "American"
    },
    {
      "id": 71716,
      "technique": null,
      "title": "Twelve sketches for wall pieces",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV032702_dynmc",
      "department": "Department of Drawings",
      "description": "Page 1 of sketchbook:\r\nTwelve sketches for twelve different wall pieces.",
      "classification": "Drawings",
      "century": "20th century",
      "dated": "7/8/1973-1/4/1974",
      "period": null,
      "medium": "Black ink on white wove paper",
      "culture": "American"
    },
    {
      "id": 162388,
      "technique": null,
      "title": "Untitled [Ships at Sea]; verso: Untitled [Ships at Sea]",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV119098_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "6/20/1932",
      "period": null,
      "medium": "Graphite on cardboard",
      "culture": "German"
    },
    {
      "id": 198426,
      "technique": null,
      "title": "Tower of the Horatii and Curiatii, Near Tivoli, Italy",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:77107_dynmc",
      "department": "Department of Drawings",
      "description": "Verso bears a transfer from the previous page.",
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1869",
      "period": null,
      "medium": "Graphite on off-white wove paper",
      "culture": "American"
    },
    {
      "id": 305551,
      "technique": null,
      "title": "Male Torso, for \"Dead Man Revived...\"",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV004499_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "c. 1811-1813",
      "period": null,
      "medium": "Black and white chalk on brown wove paper",
      "culture": "American"
    },
    {
      "id": 312397,
      "technique": null,
      "title": "Ecce Homo",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV002840_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "17th century",
      "dated": "17th century",
      "period": null,
      "medium": "Brown ink and brown wash over red chalk on cream antique laid paper",
      "culture": "Italian"
    },
    {
      "id": 309447,
      "technique": null,
      "title": "Stirrings #2",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:VRS13549_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1985",
      "period": null,
      "medium": "Pastel on white paper",
      "culture": "American"
    },
    {
      "id": 298749,
      "technique": null,
      "title": "Old Vevay",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:VRS48797_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "1869",
      "period": null,
      "medium": "Graphite and purple wash on beige wove paper",
      "culture": "British"
    },
    {
      "id": 309311,
      "technique": null,
      "title": "Harold Edgerton (1903-1990)",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:VRS16385_dynmc",
      "department": "Department of Drawings",
      "description": "Partly sealed into mat, so verso cannot be examined 3/01.",
      "classification": "Drawings",
      "century": "20th century",
      "dated": "20th century",
      "period": null,
      "medium": "Red chalk on buff wove paper",
      "culture": "American"
    },
    {
      "id": 293950,
      "technique": null,
      "title": "Agathon and Psyche, from \"Geschichte des Agathon\"",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:75161_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "18th century",
      "dated": "c. 1772",
      "period": null,
      "medium": "Black ink and gray wash, with some incising, on cream antique laid paper, verso covered with red chalk",
      "culture": "German"
    },
    {
      "id": 294646,
      "technique": null,
      "title": "Arab Horseman",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:75220_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "19th century",
      "dated": "19th century",
      "period": null,
      "medium": "Pen and brown ink over graphite on calque, unframed",
      "culture": "French"
    },
    {
      "id": 316260,
      "technique": null,
      "title": "Gaberndorf",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV116693_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "September 1953",
      "period": null,
      "medium": "Charcoal on cream laid paper",
      "culture": null
    },
    {
      "id": 167073,
      "technique": null,
      "title": "Detached Two-Family Residence, 1932: Plan and elevations for model, 1:50",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:APC1694_dynmc",
      "department": "Busch-Reisinger Museum",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1932",
      "period": null,
      "medium": "Graphite on paper",
      "culture": "German"
    },
    {
      "id": 299447,
      "technique": null,
      "title": "Young Man with Downcast Eyes",
      "division": "European and American Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:75171_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "18th century",
      "dated": "18th century",
      "period": null,
      "medium": "Red and white chalk on cream antique laid paper laid down on a decorated mount, framing lines in black ink",
      "culture": "French"
    },
    {
      "id": 298797,
      "technique": null,
      "title": "Seated Female Nude",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV003852_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "20th century",
      "period": null,
      "medium": "Graphite on oiled paper",
      "culture": "Hungarian"
    },
    {
      "id": 309630,
      "technique": null,
      "title": "Untitled",
      "division": "Modern and Contemporary Art",
      "primaryimageurl": "http://nrs.harvard.edu/urn-3:HUAM:INV006973_dynmc",
      "department": "Department of Drawings",
      "description": null,
      "classification": "Drawings",
      "century": "20th century",
      "dated": "1950-1953",
      "period": null,
      "medium": "Black ink and graphite on cream wove paper",
      "culture": "American"
    }
  ]
}
